# Default values for helm-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
hugoWebImage:
  repository: asia.gcr.io/elite-protocol-186205/hugo-web
  tag: "1.0"
  replicas: 3

resources:
  limits:
    cpu: 10m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

